// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCppW10ghFpmXhPgcB9WG3Uy5qKl4kl1zA',
    appId: '1:683997775119:android:3853bb718ad20df693ea7a',
    messagingSenderId: '683997775119',
    projectId: 'the-ceramic-studio-5b7e0',
    storageBucket: 'the-ceramic-studio-5b7e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXrbDgWuH7_YiiVsVDj_YRwhaCBZTK4M',
    appId: '1:683997775119:ios:4ad6ef098aa4b9fc93ea7a',
    messagingSenderId: '683997775119',
    projectId: 'the-ceramic-studio-5b7e0',
    storageBucket: 'the-ceramic-studio-5b7e0.firebasestorage.app',
    iosBundleId: 'com.example.tcsInvantoryManagmentSystem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGojESkmndp1gQK6wgi_0s3nDWtohlV4',
    appId: '1:683997775119:web:bb6ce211fabfdac493ea7a',
    messagingSenderId: '683997775119',
    projectId: 'the-ceramic-studio-5b7e0',
    authDomain: 'the-ceramic-studio-5b7e0.firebaseapp.com',
    storageBucket: 'the-ceramic-studio-5b7e0.firebasestorage.app',
    measurementId: 'G-2RDYQ2B6ZY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXrbDgWuH7_YiiVsVDj_YRwhaCBZTK4M',
    appId: '1:683997775119:ios:4ad6ef098aa4b9fc93ea7a',
    messagingSenderId: '683997775119',
    projectId: 'the-ceramic-studio-5b7e0',
    storageBucket: 'the-ceramic-studio-5b7e0.firebasestorage.app',
    iosBundleId: 'com.example.tcsInvantoryManagmentSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQGojESkmndp1gQK6wgi_0s3nDWtohlV4',
    appId: '1:683997775119:web:d153ce3172fcff6193ea7a',
    messagingSenderId: '683997775119',
    projectId: 'the-ceramic-studio-5b7e0',
    authDomain: 'the-ceramic-studio-5b7e0.firebaseapp.com',
    storageBucket: 'the-ceramic-studio-5b7e0.firebasestorage.app',
    measurementId: 'G-4406WS8DSS',
  );

}